-- Create Table T_ACCOUNT
CREATE TABLE T_ACCOUNT (
  A_ID INT(11) NOT NULL AUTO_INCREMENT,
  A_NAME VARCHAR(20) NOT NULL,
  A_PASSWORD VARCHAR(100) NOT NULL,
  A_DESCRIPTION VARCHAR(100) NOT NULL DEFAULT '',
  A_STATE INT(1) DEFAULT 1 NOT NULL,
  A_CREATE_TIME TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  A_UPDATE_TIME TIMESTAMP NULL,
  PRIMARY KEY (A_ID)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;