-- Create Table T_ROLE
CREATE TABLE T_ROLE (
  R_ID INT(11) NOT NULL AUTO_INCREMENT,
  R_NAME VARCHAR(20) NOT NULL,
  R_KEY VARCHAR(20) NOT NULL,
  R_DESCRIPTION VARCHAR(100) NOT NULL DEFAULT '',
  R_STATE INT(1) DEFAULT 1 NOT NULL,
  R_CREATE_TIME TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  R_UPDATE_TIME TIMESTAMP NULL,
  PRIMARY KEY (R_ID)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;