-- Create Table T_ACCOUNT_ROLE
CREATE TABLE T_ACCOUNT_ROLE (
  AR_ID INT(11) NOT NULL AUTO_INCREMENT,
  A_ID INT(11) NOT NULL,
  R_ID INT(11) NOT NULL,
  PRIMARY KEY (AR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;