-- Create Table T_RESOURCE_ROLE
CREATE TABLE T_RESOURCE_ROLE (
  RR_ID INT(11) NOT NULL AUTO_INCREMENT,
  RE_ID INT(11) NOT NULL,
  RO_ID INT(11) NOT NULL,
  PRIMARY KEY (RR_ID)
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8;